Accounts/urls.py
from django.urls import path
from .views import LoginUser, ProfileUser, RegisterUser, LogoutUser, ChangePasswordUser, ProfileUpdateView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginUser.as_view(), name='user_login'),
    path('profile/', ProfileUser.as_view(), name='user_profile'),
    path('register/', RegisterUser.as_view(), name='user_register'),
    path('logout/', LogoutUser.as_view(), name='user_logout'),
    path('change/password/', ChangePasswordUser.as_view(), name='user_change_password'),
    path('profile/update/', ProfileUpdateView.as_view(), name='update_profile'),

]

ProjectManager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('Accounts.urls')),
    path('', include('Projects.urls')),
    path('', include('pwa.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from Projects.models import Project, Task, SubTask


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=12, unique=True)
    image = models.ImageField(upload_to='accounts/profile/',
                              default='accounts/profile/default/default_avatar.jpg')

    def __str__(self):
        return self.user.username

    @property
    def all_project(self):
        count = 0
        all_pj = Project.objects.filter(user=self.user)
        for pj in all_pj:
            count += 1
        return count

    @property
    def all_task(self):
        count = 0
        all_task = Task.objects.filter(project__user=self.user)
        for task in all_task:
            count += 1
        return count

    @property
    def all_sub_task(self):
        count = 0
        all_sub = SubTask.objects.filter(task__project__user=self.user)
        for sub in all_sub:
            count += 1
        return count

    @property
    def count_project(self):
        if self.all_project != 0:
            count = 0
            done = 0
            all_pj = Project.objects.filter(user=self.user)
            for pj in all_pj:
                count += 1
                if pj.status is True:
                    done += 1
            avg = (done / count)
            percentage = avg * 100
            return int(percentage)
        else:
            return 0

    @property
    def count_task(self):
        if self.all_task != 0:
            count = 0
            done = 0
            all_task = Task.objects.filter(project__user=self.user)
            for task in all_task:
                count += 1
                if task.status is True:
                    done += 1
            avg = (done / count)
            percentage = avg * 100
            return int(percentage)
        else:
            return 0

    @property
    def count_sub_task(self):
        if self.all_sub_task != 0:
            count = 0
            done = 0
            all_sub = SubTask.objects.filter(task__project__user=self.user)
            for sub in all_sub:
                count += 1
                if sub.status is True:
                    done += 1

            avg = (done / count)
            percentage = avg * 100
            return int(percentage)
        else:
            return 0

Accounts/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django import forms
from django.contrib.auth.models import User
from .models import Profile


class UserRegisterForm(forms.ModelForm):
    password_1 = forms.CharField(max_length=100, required=True,
                                 widget=forms.TextInput(
                                     attrs={
                                         'class': 'form-control',
                                         'id': 'form3Example5',
                                         'type': 'password',
                                     }
                                 ))
    username = forms.CharField(required=True, max_length=50,
                               widget=forms.TextInput(
                                   attrs={
                                       'class': 'form-control',
                                       'id': 'form3Example1'
                                   }
                               ))
    email = forms.EmailField(required=True, max_length=175,
                             widget=forms.TextInput(
                                 attrs={
                                     'class': 'form-control',
                                     'id': 'form3Example2'
                                 }
                             ))
    first_name = forms.CharField(required=True, max_length=50,
                                 widget=forms.TextInput(
                                     attrs={
                                         'class': 'form-control',
                                         'id': 'form3Example3'
                                     }
                                 ))
    last_name = forms.CharField(required=True, max_length=50,
                                widget=forms.TextInput(
                                    attrs={
                                        'class': 'form-control',
                                        'id': 'form3Example4'
                                    }
                                ))
    phone_number = forms.CharField(required=True, max_length=12,
                                   widget=forms.TextInput(
                                       attrs={
                                           'class': 'form-control',
                                           'id': 'form3Example7',
                                           'name': 'phone_number'
                                       }
                                   ))

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', ]

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('this user name was taken')
        return username

    def clean_password_1(self):
        password1 = self.cleaned_data['password_1']
        if len(password1) < 8:
            raise forms.ValidationError('something went wrong')
        return password1

    def clean_phone_number(self):
        phone_number = self.cleaned_data['phone_number']
        if Profile.objects.filter(phone=phone_number).exists():
            raise forms.ValidationError('this phone already exists')
        return phone_number


class UserLoginForm(AuthenticationForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'id': 'form3Example4'}))
    remember = forms.BooleanField(required=False,
                                  widget=forms.CheckboxInput(
                                      attrs={
                                          'class': 'form-check-input me-2',
                                          'id': 'form2Example33'
                                      }
                                  ))
    username = forms.CharField(
        required=True, max_length=100,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'id': 'form3Example1'
            }
        )
    )

    def __init__(self, *args, **kwargs):
        self.error_messages['invalid_login'] = 'username or password is incorrect'
        super().__init__(*args, **kwargs)


class UserProfileUpdateForm(forms.ModelForm):
    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=30, required=False)
    email = forms.EmailField(required=True)

    class Meta:
        model = Profile
        fields = ['phone', 'image']

    def __init__(self, *args, **kwargs):
        # Pop the user instance from the kwargs and pass it to both forms
        user = kwargs.pop('user', None)
        super(UserProfileUpdateForm, self).__init__(*args, **kwargs)

        # If a user is passed, prepopulate User fields
        if user:
            self.fields['first_name'].initial = user.first_name
            self.fields['last_name'].initial = user.last_name
            self.fields['email'].initial = user.email

    def save(self, commit=True):
        profile = super(UserProfileUpdateForm, self).save(commit=False)

        # Save the User model fields
        user = profile.user
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
            profile.save()
        return profile

Accounts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import views as auth_views
from .forms import UserLoginForm, UserRegisterForm, UserProfileUpdateForm
from django.contrib import messages
from django.views.generic import View, UpdateView
from .models import Profile
from django.contrib.auth.models import User
from django.contrib.auth import login, logout
from django.contrib.auth.views import PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls.base import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin


class RegisterUser(View):
    form_class = UserRegisterForm
    template_name = 'Accounts/register.html'

    def get(self, *args, **kwargs):
        return render(self.request, self.template_name, {'form': self.form_class})

    def post(self, *args, **kwargs):
        form = self.form_class(self.request.POST)
        if form.is_valid():
            data = form.cleaned_data
            print(data)
            user = User.objects.create_user(username=data['username'],
                                            email=data['email'],
                                            last_name=data['last_name'],
                                            first_name=data['first_name'],
                                            password=data['password_1'])
            Profile.objects.create(
                user=user,
                phone=data['phone_number'],
            )
            login(self.request, user)
            messages.success(self.request, f"welcome", 'success')
            return redirect('accounts:user_profile')
        return render(self.request, self.template_name, {"form": form})


class LoginUser(auth_views.LoginView):
    form_class = UserLoginForm
    template_name = 'Accounts/login.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('accounts:user_profile')
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        remember = form.cleaned_data['remember']
        if remember:
            self.request.session.set_expiry(172800)  # expired after 2 days
        else:
            self.request.session.set_expiry(0)  # expired after user close the browser
        self.request.session.modified = True

        messages.success(self.request, f"welcome", 'success')
        return super(LoginUser, self).form_valid(form)


class ProfileUser(View):
    def get(self, *args, **kwargs):
        request = self.request
        profile = get_object_or_404(Profile, user=request.user)
        context = {
            'profile': profile
        }
        return render(request, 'Accounts/profile.html', context)


class LogoutUser(View):

    def get(self, request):
        logout(request)
        messages.success(self.request, f"We Hope See You Again !!", 'success')
        return redirect('accounts:user_login')


class ChangePasswordUser(SuccessMessageMixin, PasswordChangeView):
    template_name = 'Accounts/change_password.html'
    success_message = 'Password was changed successfully'
    success_url = reverse_lazy('accounts:user_profile')


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = Profile
    form_class = UserProfileUpdateForm
    template_name = 'accounts/update_profile.html'
    success_url = reverse_lazy('accounts:user_profile')  # Redirect after successful update

    def get_form_kwargs(self):
        """Pass the current user to the form."""
        kwargs = super().get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def get_object(self, queryset=None):
        """Return the profile of the logged-in user."""
        return self.request.user.profile

    def form_valid(self, form):
        """If the form is valid, save both the user and profile."""
        form.save()
        messages.success(self.request, 'Your profile has been updated successfully!')
        return super().form_valid(form)

Accounts/templates/Accounts/change_password.html
{% extends 'base.html' %}
{% block title %} Change Password {% endblock %}
{% block content %}
    <br><br><br><br>
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                        <div class="card-header justify-content-center">
                            <h3 class="font-weight-light my-4 text-center">Change Your Password</h3>
                        </div>
                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <div class="col-md-10 offset-md-1">
                                    <div class="form-group mt-0 mb-1">
                                        <button type="submit" class="col-md-12 btn btn-success mt-3" id="reset">Update
                                            Password
                                        </button>
                                        <a href="{% url 'accounts:user_profile' %}" class="col-md-12 btn btn-outline-danger mt-3"
                                           id="reset">
                                            Cancel
                                        </a>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Accounts/templates/Accounts/login.html
{% extends 'base.html' %}
{% block title %}ProjectManager login page{% endblock %}

{% block content %}
    <section class="background-radial-gradient overflow-hidden">


    <div class="container px-4 py-5 px-md-5 text-center text-lg-start my-5">
        <div class="row gx-lg-5 align-items-center mb-5">
            <div class="col-lg-6 mb-5 mb-lg-0" style="z-index: 10">
                <h1 class="my-5 display-5 fw-bold ls-tight" style="color: hsl(218, 81%, 95%)">
                    The best offer <br/>
                    <span style="color: hsl(218, 81%, 75%)">for your business</span>
                </h1>
                <p class="mb-4 opacity-70" style="color: hsl(218, 81%, 85%)">
                    Lorem ipsum dolor, sit amet consectetur adipisicing elit.
                    Temporibus, expedita iusto veniam atque, magni tempora mollitia
                    dolorum consequatur nulla, neque debitis eos reprehenderit quasi
                    ab ipsum nisi dolorem modi. Quos?
                </p>
            </div>

            <div class="col-lg-6 mb-5 mb-lg-0 position-relative">
                <div id="radius-shape-1" class="position-absolute rounded-circle shadow-5-strong"></div>
                <div id="radius-shape-2" class="position-absolute shadow-5-strong"></div>

                <div class="card bg-glass">
                    <div class="card-body px-4 py-5 px-md-5">
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary btn-block mb-4">
                                Sign In
                            </button>
                            <a href="#" class="btn btn-outline-primary btn-block mb-4">Sign Up</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

Accounts/templates/Accounts/profile.html
{% extends 'base.html' %}
{% block title %}profile user page{% endblock %}
{% block content %}
    <br><br>
    <div class="container">
        <div class="main-body">
            <div class="row">
                <div class="col-lg-4">
                    <div class="card">
                        <div class="card-body">
                            <div class="d-flex flex-column align-items-center text-center">
                                <img src="{{ profile.image.url }}"
                                    alt="Admin" class="rounded-circle p-1 bg-primary" width="110">
                                <div class="mt-3">
                                    <h4>{{ profile.user.first_name }} {{ profile.user.last_name }}</h4>
                                    <p class="text-secondary mb-1">@{{ profile.user.username }}</p>
                                    <p class="text-muted font-size-sm">{{ profile.user.email }}</p>
                                    <p class="text-muted font-size-sm">{{ profile.phone }}</p>
                                    <a class="btn btn-primary" href="{% url 'accounts:user_change_password' %}">Change Password</a>
                                    <a class="btn btn-primary" href="{% url 'accounts:update_profile' %}">Update info</a>

                                </div>
                            </div>
                            <hr class="my-4">
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                    <h6 class="mb-0">All Projects: </h6>
                                    <span class="text-secondary">{{ profile.all_project }}</span>
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                    <h6 class="mb-0">All Tasks: </h6>
                                    <span class="text-secondary">{{ profile.all_task }}</span>
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                    <h6 class="mb-0">All SubTasks: </h6>
                                    <span class="text-secondary">{{ profile.all_sub_task }}</span>
                                </li>

                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="card">
                                <div class="card-body">
                                    <h5 class="d-flex align-items-center mb-3">Project Progressbar</h5>
                                    <p>Project</p>
                                    <div class="progress mb-3" style="height: 5px">
										<div class="progress-bar bg-primary" role="progressbar" style="width: {{ profile.count_project }}%" aria-valuenow="{{ profile.count_project }}" aria-valuemin="0" aria-valuemax="100"></div>
									</div>
									<p>Task</p>
									<div class="progress mb-3" style="height: 5px">
										<div class="progress-bar bg-danger" role="progressbar" style="width: {{ profile.count_task }}%" aria-valuenow="{{ profile.count_task }}" aria-valuemin="0" aria-valuemax="100"></div>
									</div>
									<p>Sub Task</p>
									<div class="progress mb-3" style="height: 5px">
										<div class="progress-bar bg-success" role="progressbar" style="width: {{ profile.count_sub_task }}%" aria-valuenow="{{ profile.count_sub_task }}" aria-valuemin="0" aria-valuemax="100"></div>
									</div>


                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Accounts/templates/Accounts/register.html
{% extends 'base.html' %}

{% block title %}{% endblock %}
{% block content %}
    <style>
            .background-radial-gradient {
                background-color: hsl(218, 41%, 15%);
                background-image: radial-gradient(650px circle at 0% 0%,
                hsl(218, 41%, 35%) 15%,
                hsl(218, 41%, 30%) 35%,
                hsl(218, 41%, 20%) 75%,
                hsl(218, 41%, 19%) 80%,
                transparent 100%),
                radial-gradient(1250px circle at 100% 100%,
                        hsl(218, 41%, 45%) 15%,
                        hsl(218, 41%, 30%) 35%,
                        hsl(218, 41%, 20%) 75%,
                        hsl(218, 41%, 19%) 80%,
                        transparent 100%);
            }

            #radius-shape-1 {
                height: 220px;
                width: 220px;
                top: -60px;
                left: -130px;
                background: radial-gradient(#44006b, #ad1fff);
                overflow: hidden;
            }

            #radius-shape-2 {
                border-radius: 38% 62% 63% 37% / 70% 33% 67% 30%;
                bottom: -60px;
                right: -110px;
                width: 300px;
                height: 300px;
                background: radial-gradient(#44006b, #ad1fff);
                overflow: hidden;
            }

            .bg-glass {
                background-color: hsla(0, 0%, 100%, 0.9) !important;
                backdrop-filter: saturate(200%) blur(25px);
            }
        </style>
    <section class="background-radial-gradient overflow-hidden">
        <div class="container px-4 py-5 px-md-5 text-center text-lg-start my-5">
            <div class="row gx-lg-5 align-items-center mb-5">
                <div class="col-lg-6 mb-5 mb-lg-0" style="z-index: 10">
                    <h1 class="my-5 display-5 fw-bold ls-tight" style="color: hsl(218, 81%, 95%)">
                        The best offer <br/>
                        <span style="color: hsl(218, 81%, 75%)">for your business</span>
                    </h1>
                    <p class="mb-4 opacity-70" style="color: hsl(218, 81%, 85%)">
                        Lorem ipsum dolor, sit amet consectetur adipisicing elit.
                        Temporibus, expedita iusto veniam atque, magni tempora mollitia
                        dolorum consequatur nulla, neque debitis eos reprehenderit quasi
                        ab ipsum nisi dolorem modi. Quos?
                    </p>
                </div>

                <div class="col-lg-6 mb-5 mb-lg-0 position-relative">
                    <div id="radius-shape-1" class="position-absolute rounded-circle shadow-5-strong"></div>
                    <div id="radius-shape-2" class="position-absolute shadow-5-strong"></div>

                    <div class="card bg-glass">
                        <div class="card-body px-4 py-5 px-md-5">
                            <form method="post">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit" class="btn btn-primary btn-block mb-4">
                                    Sign up
                                </button>
                                <a href="{% url 'accounts:user_login' %}" class="btn btn-outline-primary btn-block mb-4">Sign In</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

Accounts/templates/Accounts/update_profile.html
{% extends 'base.html' %}
{% block title %}Update Profile{% endblock %}
{% block content %}
    <br><br><br><br>
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                        <div class="card-header justify-content-center">
                            <h3 class="font-weight-light my-4 text-center">Change Your Password</h3>
                        </div>
                        <div class="card-body">
                            <form method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <div class="col-md-10 offset-md-1">
                                    <div class="form-group mt-0 mb-1">
                                        <button type="submit" class="col-md-12 btn btn-success mt-3" id="reset">Update
                                            Profile
                                        </button>
                                        <a href="{% url 'accounts:user_profile' %}" class="col-md-12 btn btn-outline-danger mt-3"
                                           id="reset">
                                            Cancel
                                        </a>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{#  <h2>Update Profile</h2>#}
{#  <form method="POST" enctype="multipart/form-data">#}
{#    {% csrf_token %}#}
{#    {{ form.as_p }}#}
{#    <button type="submit" class="btn btn-primary">Update Profile</button>#}
{#  </form>#}
{% endblock %}