Accounts/urls.py
from django.urls import path
from .views import LoginUser, ProfileUser, RegisterUser, LogoutUser, ChangePasswordUser, ProfileUpdateView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginUser.as_view(), name='user_login'),
    path('profile/', ProfileUser.as_view(), name='user_profile'),
    path('register/', RegisterUser.as_view(), name='user_register'),
    path('logout/', LogoutUser.as_view(), name='user_logout'),
    path('change/password/', ChangePasswordUser.as_view(), name='user_change_password'),
    path('profile/update/', ProfileUpdateView.as_view(), name='update_profile'),

]

ProjectManager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('Accounts.urls')),
    path('', include('Projects.urls')),
    path('', include('pwa.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Projects/urls.py
from django.urls import path
from .views import ProjectListView, ProjectCreateView, ProjectDeleteView, UpdateProjectView

app_name = 'projects'

urlpatterns = [
    path('', ProjectListView.as_view(), name='projects_list'),
    path('create/project', ProjectCreateView.as_view(), name='project_create'),
    path('delete/project/<int:pk>/', ProjectDeleteView.as_view(), name='project_delete'),
    path('update/project/<int:pk>/', UpdateProjectView.as_view(), name='project_update'),
]

Projects/forms.py
from django import forms
from .models import Project, Task, SubTask


class ProjectForm(forms.ModelForm):
    color_option = (
        ('red', 'red'),
        ('black', 'black'),
        ('blue', 'blue'),
        ('green', 'green'),
        ('gray', 'gray'),
        ('pink', 'pink'),
        ('yellow', 'yellow'),
    )
    title = forms.CharField(max_length=256, required=True,
                            widget=forms.TextInput(attrs={'class': 'form-control'}))
    image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control'}))
    color = forms.ChoiceField(choices=color_option, widget=forms.Select(attrs={'class': 'form-control'}))
    description = forms.CharField(required=True, widget=forms.Textarea(attrs={'class': 'form-control'}))
    budget = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control'}))
    start_date = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}))
    end_date = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}))

    class Meta:
        model = Project
        fields = (
            'title',
            'image',
            'color',
            'budget',
            'start_date',
            'end_date',
            'description',
        )


class ProjectUpdateForm(forms.ModelForm):
    color_option = (
        ('red', 'red'),
        ('black', 'black'),
        ('blue', 'blue'),
        ('green', 'green'),
        ('gray', 'gray'),
        ('pink', 'pink'),
        ('yellow', 'yellow'),
    )
    title = forms.CharField(max_length=256, required=True,
                            widget=forms.TextInput(attrs={'class': 'form-control'}))
    image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control'}))
    color = forms.ChoiceField(choices=color_option, widget=forms.Select(attrs={'class': 'form-control'}))
    description = forms.CharField(required=True, widget=forms.Textarea(attrs={'class': 'form-control'}))
    budget = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control'}))
    start_date = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}))
    end_date = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}))

    class Meta:
        model = Project
        fields = (
            'title',
            'image',
            'color',
            'budget',
            'start_date',
            'end_date',
            'description',
            'status'
        )


class TaskForm(forms.ModelForm):
    color_option = (
        ('black', 'black'),
        ('blue', 'blue'),
        ('gray', 'gray'),
        ('red', 'red'),
        ('green', 'green'),
        ('orange', 'orange'),
        ('pink', 'pink'),
    )
    title = forms.CharField(max_length=100,
                            required=True,
                            widget=forms.TextInput(attrs={'class': 'form-control'}))
    image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control'}))
    color = forms.ChoiceField(choices=color_option, widget=forms.Select(attrs={'class': 'form-control'}))
    descriptions = forms.CharField(required=True, widget=forms.Textarea(attrs={'class': 'form-control'}))
    budget = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control'}))
    start_date = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}))
    end_date = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}))

    class Meta:
        model = Task
        fields = (
            'title',
            'image',
            'color',
            'budget',
            'start_date',
            'end_date',
            'descriptions',
        )


class UpdateTaskForm(forms.ModelForm):
    color_option = (
        ('black', 'black'),
        ('blue', 'blue'),
        ('gray', 'gray'),
        ('red', 'red'),
        ('green', 'green'),
        ('orange', 'orange'),
        ('pink', 'pink'),
    )
    title = forms.CharField(max_length=100,
                            required=True,
                            widget=forms.TextInput(attrs={'class': 'form-control'}))
    image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control'}))
    color = forms.ChoiceField(choices=color_option, widget=forms.Select(attrs={'class': 'form-control'}))
    descriptions = forms.CharField(required=True, widget=forms.Textarea(attrs={'class': 'form-control'}))
    budget = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control'}))
    start_date = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}))
    end_date = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}))
    status = forms.BooleanField(widget=forms.CheckboxInput(attrs={'type': 'checkbox'}))

    class Meta:
        model = Task
        fields = (
            'title',
            'image',
            'color',
            'budget',
            'start_date',
            'end_date',
            'descriptions',
            'status'
        )


class SubTaskForm(forms.ModelForm):
    color_option = (
        ('black', 'black'),
        ('blue', 'blue'),
        ('gray', 'gray'),
        ('red', 'red'),
        ('green', 'green'),
        ('orange', 'orange'),
        ('pink', 'pink'),
    )
    title = forms.CharField(max_length=100,
                            required=True,
                            widget=forms.TextInput(attrs={'class': 'form-control'}))
    image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control'}))
    color = forms.ChoiceField(choices=color_option, widget=forms.Select(attrs={'class': 'form-control'}))
    descriptions = forms.CharField(required=True, widget=forms.Textarea(attrs={'class': 'form-control'}))
    budget = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control'}))
    start_date = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}))
    end_date = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}))

    class Meta:
        model = SubTask
        fields = (
            'title',
            'image',
            'color',
            'descriptions',
            'budget',
            'start_date',
            'end_date',
        )


class UpdateSubTaskForm(forms.ModelForm):
    color_option = (
        ('black', 'black'),
        ('blue', 'blue'),
        ('gray', 'gray'),
        ('red', 'red'),
        ('green', 'green'),
        ('orange', 'orange'),
        ('pink', 'pink'),
    )
    title = forms.CharField(max_length=100,
                            required=True,
                            widget=forms.TextInput(attrs={'class': 'form-control'}))
    image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control'}))
    color = forms.ChoiceField(choices=color_option, widget=forms.Select(attrs={'class': 'form-control'}))
    descriptions = forms.CharField(required=True, widget=forms.Textarea(attrs={'class': 'form-control'}))
    budget = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control'}))
    start_date = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}))
    end_date = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}))
    status = forms.BooleanField(widget=forms.CheckboxInput(attrs={'type': 'checkbox'}))

    class Meta:
        model = Task
        fields = (
            'title',
            'image',
            'color',
            'budget',
            'start_date',
            'end_date',
            'descriptions',
            'status'
        )

Projects/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .models import Project, Task, SubTask
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import ProjectForm, ProjectUpdateForm, TaskForm, UpdateTaskForm, SubTaskForm, UpdateSubTaskForm
from django.contrib.auth.models import User


class ProjectListView(LoginRequiredMixin, ListView):
    """
    this view will return all of the projects
    """
    login_url = 'accounts/login/'

    def get(self, request, *args, **kwargs):
        projects = Project.objects.filter(user=request.user)
        context = {
            'projects': projects
        }
        return render(request, 'Projects/projects.html', context)


class ProjectCreateView(CreateView):
    """
    this view give us create function for project model
    """

    form_class = ProjectForm
    template_name = 'Projects/create_project.html'

    def post(self, request, *args, **kwargs):
        user = request.user
        form = self.form_class(request.POST, request.FILES, )
        if form.is_valid():
            data = form.cleaned_data
            project = Project.objects.create(
                user=user,
                title=data['title'], image=data['image'],
                description=data['description'], color=data['color'],
                start_date=data['start_date'], end_date=data['end_date'],
                budget=data['budget']
            )
            if project:
                messages.success(request, 'your project saved', 'success')
                return redirect('projects:projects_list')
            messages.error(request, 'something went wrong !!!', 'danger')
        else:
            form = self.form_class()
        return render(request, 'Projects/create_project.html', {"form": form})


class ProjectDeleteView(DeleteView):
    """
        ...
    """
    model = Project
    pk_url_kwarg = 'pk'
    template_name = 'Projects/confirm_delete_pj.html'
    success_url = '/'


class UpdateProjectView(UpdateView):
    """
    ...
    """
    model = Project
    form_class = ProjectUpdateForm
    pk_url_kwarg = 'pk'
    template_name = 'Projects/update.html'
    success_url = '/'


class TaskListView(ListView):
    """
        this views give us detail of project and all task of this project
        """

    def get(self, request, *args, **kwargs):
        projects = get_object_or_404(Project, id=kwargs['id'])
        tasks = Task.objects.filter(project=projects)

        context = {
            'projects': projects,
            'tasks': tasks,
        }
        return render(request, 'Projects/task.html', context)


class DeleteTask(DeleteView):
    """
        this views give us delete func of task
        """
    model = Task
    pk_url_kwarg = 'pk'
    template_name = 'Projects/confirm_delete_ts.html'
    success_url = '/'


class UpdateTask(UpdateView):
    """
        this views give us update task func
        """
    model = Task
    form_class = UpdateTaskForm
    pk_url_kwarg = 'pk'
    template_name = 'Projects/update_ts.html'
    success_url = '/'


class AllTaskListView(ListView):
    """
        this views give us all task of this user
        """

    def get(self, request, *args, **kwargs):
        tasks = Task.objects.filter(project__user=request.user)
        context = {
            'tasks': tasks,
        }
        return render(request, 'Projects/all_tasks.html', context)


class TaskCreateView(CreateView):
    """
    this views give us create function for task model
    """
    form_class = TaskForm
    template_name = 'Projects/create_task.html'

    def post(self, request, *args, **kwargs):
        user = request.user
        form = self.form_class(request.POST, request.FILES, instance=user)
        project = Project.objects.get(id=self.kwargs['id'])
        if form.is_valid():
            data = form.cleaned_data
            task = Task.objects.create(
                project=project, image=data['image'],
                color=data['color'], descriptions=data['descriptions'],
                start_date=data['start_date'], end_date=data['end_date'], title=data['title']
            )
            if task:
                messages.success(request, 'your task saved success', 'success')
                return redirect('project:all_task', project.id)
            else:
                messages.error(request, 'somthing went wrong !!', 'danger')
                return redirect('project:all_task', project.id)

        else:
            form = self.form_class(instance=user)
        return render(request, 'Projects/create_task.html', {"form": form})


class TaskAndSubTaskListView(ListView):
    """
        this views give us detail of task and subtask
        """

    def get(self, request, *args, **kwargs):
        user = User.objects.get(id=request.user.id)
        task = get_object_or_404(Task, id=kwargs['id'])
        sub_task = SubTask.objects.filter(task=task)

        context = {
            'task': task,
            'sub_task': sub_task,
        }
        return render(request, 'Projects/task_detail.html', context)


class SubTaskCreateView(CreateView):
    """
    this views give us create function for subtask model
    """
    form_class = SubTaskForm
    template_name = 'Projects/create_subtask.html'

    def post(self, request, *args, **kwargs):
        user = request.user
        form = self.form_class(request.POST, request.FILES, instance=user)
        task = Task.objects.get(id=self.kwargs['id'])
        if form.is_valid():
            data = form.cleaned_data
            sub_task = SubTask.objects.create(
                task=task, image=data['image'],
                color=data['color'], descriptions=data['descriptions'],
                start_date=data['start_date'], end_date=data['end_date'], title=data['title']
            )
            if sub_task:
                messages.success(request, 'your sub task saved success', 'success')
                return redirect('project:task_detail', task.id)
            else:
                messages.error(request, 'somthing went wrong !!', 'danger')
                return redirect('project:task_detail', task.id)

        else:
            form = self.form_class(instance=user)
        return render(request, 'Projects/create_subtask.html', {"form": form})


class DeleteSubTask(DeleteView):
    """
        this views give us delete func of subtask model
        """
    model = SubTask
    pk_url_kwarg = 'pk'
    template_name = 'Projects/confirm_delete_st.html'
    success_url = '/'


class UpdateSubTask(UpdateView):
    """
        this views give us update func for subtask model
        """
    model = SubTask
    form_class = UpdateSubTaskForm
    pk_url_kwarg = 'pk'
    template_name = 'Projects/update_st.html'
    success_url = '/'


class SubTaskView(ListView):
    """
            this views give us detail of subtask
            """

    def get(self, request, *args, **kwargs):
        sub_task = get_object_or_404(SubTask, id=kwargs['id'])

        context = {
            'sub_task': sub_task,
        }
        return render(request, 'Projects/subtask.html', context)

Projects/templates/Projects/all_tasks.html
{% extends 'base.html' %}
{% block body %}
    <section class="d-flex justify-content-center">
        <div class="row d-flex justify-content-center" style="margin-left: 100px">
            {% for task in tasks %}
                <div class="col-lg-4" style="text-align: center">
                    <div class="card m-3" style="width: 18rem;">
                        <img src="{{ task.image.url }}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{ task.title }}</h5>
                            <p class="card-text">{{ task.descriptions }}</p>
                            <a href="{% url 'project:task_detail' task.id %}" class="btn btn-primary">More Info</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </section>
{% endblock %}

Projects/templates/Projects/confirm_delete_pj.html
{% include 'base.html' %}
{% block body %}

    <div class="container px-4 py-5 px-md-5 text-center text-lg-start my-5">
        <div class="row gx-lg-5 align-items-center mb-5">
            <div class="col-lg-3 mb-5 mb-lg-0" style="z-index: 10">
                <h1>Delete Project</h1>
            </div>

            <div class="col-lg-6 mb-5 mb-lg-0 position-relative">
                <div id="radius-shape-1" class="position-absolute rounded-circle shadow-5-strong"></div>
                <div id="radius-shape-2" class="position-absolute shadow-5-strong"></div>

                <div class="card bg-glass" style="background-color: rgba(87,101,107,0.5); color: #ced6de">
                    <div class="card-body px-4 py-5 px-md-5">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-6 mb-4 text-center container">
                                    <div class="form-outline">
                                        <p>Are you sure you want to delete "{{ object.title }}"?</p>
                                    </div>
                                </div>
                            </div>
                            <button class="btn btn-danger container" type="submit">Delete</button>

                            <a class="btn btn-outline-secondary container mt-3" href="{% url 'projects:projects_list' %}">Cancel</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

Projects/templates/Projects/confirm_delete_st.html
{% include 'base.html' %}
{% block body %}

    <div class="container px-4 py-5 px-md-5 text-center text-lg-start my-5">
        <div class="row gx-lg-5 align-items-center mb-5">
            <div class="col-lg-3 mb-5 mb-lg-0" style="z-index: 10">
                <h1>Delete Sub Task</h1>
            </div>

            <div class="col-lg-6 mb-5 mb-lg-0 position-relative">
                <div id="radius-shape-1" class="position-absolute rounded-circle shadow-5-strong"></div>
                <div id="radius-shape-2" class="position-absolute shadow-5-strong"></div>

                <div class="card bg-glass" style="background-color: rgba(87,101,107,0.5); color: #ced6de">
                    <div class="card-body px-4 py-5 px-md-5">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-6 mb-4 text-center container">
                                    <div class="form-outline">
                                        <p>Are you sure you want to delete "{{ object.title }}"?</p>
                                    </div>
                                </div>
                            </div>
                            <button class="btn btn-danger container" type="submit">Delete</button>

                            <a class="btn btn-outline-secondary container mt-3" href="{% url 'project:task_detail' subtask.id %}">Cancel</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

Projects/templates/Projects/confirm_delete_ts.html
{% include 'base.html' %}
{% block body %}

    <div class="container px-4 py-5 px-md-5 text-center text-lg-start my-5">
        <div class="row gx-lg-5 align-items-center mb-5">
            <div class="col-lg-3 mb-5 mb-lg-0" style="z-index: 10">
                <h1>Delete Project</h1>
            </div>

            <div class="col-lg-6 mb-5 mb-lg-0 position-relative">
                <div id="radius-shape-1" class="position-absolute rounded-circle shadow-5-strong"></div>
                <div id="radius-shape-2" class="position-absolute shadow-5-strong"></div>

                <div class="card bg-glass" style="background-color: rgba(87,101,107,0.5); color: #ced6de">
                    <div class="card-body px-4 py-5 px-md-5">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-6 mb-4 text-center container">
                                    <div class="form-outline">
                                        <p>Are you sure you want to delete "{{ object.title }}"?</p>
                                    </div>
                                </div>
                            </div>
                            <button class="btn btn-danger container" type="submit">Delete</button>

                            <a class="btn btn-outline-secondary container mt-3" href="{% url 'project:task_detail' task.id %}">Cancel</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

Projects/templates/Projects/create_project.html
{% extends 'base.html' %}
{% block title %} Create New Project {% endblock %}

{% block content %}

    <div class="container px-4 py-5 px-md-5 text-center text-lg-start my-5">
        <div class="row gx-lg-5 align-items-center mb-5">
            <div class="col-lg-3 mb-5 mb-lg-0" style="z-index: 10">
                <h1>Create Project</h1>
            </div>
            <div class="col-lg-6 mb-5 mb-lg-0 position-relative">
                <div id="radius-shape-1" class="position-absolute rounded-circle shadow-5-strong"></div>
                <div id="radius-shape-2" class="position-absolute shadow-5-strong"></div>

                <div class="card bg-glass" style="background-color: rgba(87,101,107,0.5); color: #ced6de">
                    <div class="card-body px-4 py-5 px-md-5">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button class="btn btn-primary container" type="submit">save</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Projects/templates/Projects/create_subtask.html
{% include 'base.html' %}
{% block body %}

    <div class="container px-4 py-5 px-md-5 text-center text-lg-start my-5">
        <div class="row gx-lg-5 align-items-center mb-5">
            <div class="col-lg-3 mb-5 mb-lg-0" style="z-index: 10">
                <h1>Create Sub Task</h1>
            </div>

            <div class="col-lg-6 mb-5 mb-lg-0 position-relative">
                <div id="radius-shape-1" class="position-absolute rounded-circle shadow-5-strong"></div>
                <div id="radius-shape-2" class="position-absolute shadow-5-strong"></div>

                <div class="card bg-glass" style="background-color: rgba(87,101,107,0.5); color: #ced6de">
                    <div class="card-body px-4 py-5 px-md-5">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-6 mb-4 text-center container">
                                    <div class="form-outline">
                                        {{ form.as_div }}
                                    </div>
                                </div>
                            </div>
                            <button class="btn btn-primary container" type="submit">save</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

Projects/templates/Projects/create_task.html
{% include 'base.html' %}

{% block body %}
    <div class="container px-4 py-5 px-md-5 text-center text-lg-start my-5">
        <div class="row gx-lg-5 align-items-center mb-5">
            <div class="col-lg-3 mb-5 mb-lg-0" style="z-index: 10">
                <h1>Create Task</h1>
            </div>

            <div class="col-lg-6 mb-5 mb-lg-0 position-relative">
                <div id="radius-shape-1" class="position-absolute rounded-circle shadow-5-strong"></div>
                <div id="radius-shape-2" class="position-absolute shadow-5-strong"></div>

                <div class="card bg-glass" style="background-color: rgba(87,101,107,0.5); color: #ced6de">
                    <div class="card-body px-4 py-5 px-md-5">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-6 mb-4 text-center container">
                                    <div class="form-outline">
                                        {{ form.as_div }}
                                    </div>
                                </div>
                            </div>
                            <button class="btn btn-primary container" type="submit">save</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Projects/templates/Projects/projects.html
{% extends 'base.html' %}
{% block title %} List of Projects {% endblock %}
{% block content %}

    <div class="container mt-4">
        <a href="{% url 'projects:project_create' %}" class="btn bg-success">new project</a>
        <div class="row">
            {% for project in projects %}
                <div class="col-4 mt-2 mb-4">
                <div class="all-cart">
                    <div class="col">
                        <div class="card h-100" style="border-color: {{ project.color }}">
                            <img src="{{ project.image.url }}" class="card-img-top" alt="{{ project.title }}">
                            <div class="card-body">
                                <h5 class="card-title">{{ project.title }}</h5>
                                <p style="background-color: {{ project.color }};width: 20px;height: 20px;border-radius: 20px"></p>
                            </div>
                            <div class="card-footer">
                                <a href="#" class="btn btn-primary">More Info</a>
                                <small class="text-body-secondary">{{ project.start_date }}</small>
                                <small class="text-body-secondary">{{ project.end_date }}</small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

Projects/templates/Projects/subtask.html
{% include 'base.html' %}

{% block body %}<br>
    <div class="container">
        <div class="row">
            <h2 style="text-align: center">information of Sub Task</h2>
            <div class="col-4 mt-5">
                <h3> project: {{ sub_task.title }}</h3>
                <div class="form-check form-switch">
                    <label class="form-check-label" for="flexSwitchCheckDefault">Sub Task Status:</label>
                    {% if sub_task.status is False %}
                        <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault">
                    {% else %}
                        <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault" checked>
                    {% endif %}
                </div>
                <p>start: {{ sub_task.start }}</p>
                <p>end: {{ sub_task.end }}</p>
                <p style="background-color: {{ sub_task.color }};width: 40px;height: 40px;border-radius: 40px"></p>
                <p>budget : {{ sub_task.budget }}</p>
            </div>
            <div class="col-4 mt-5">
                <h4>description:</h4>
                <p>{{ sub_task.descriptions }}</p>


                <a href="{% url 'project:done_st' sub_task.pk %}" class="btn btn-primary mt-5">Update</a>
                <a href="{% url 'project:delete_st' sub_task.pk %}" class="btn btn-danger mt-5">Delete</a>
                <a href="{% url 'project:all_pj' %}" class="btn btn-outline-danger mt-5">Back</a>
            </div>
            <div class="col-4 mt-5">
                <img src="{{ sub_task.image.url }}"
                     width="100%" height="200px"
                     style="border-color: black;border-radius: 30px;box-shadow: rgba(0,0,0,0.2) 10px 10px 10px 10px">

            </div>
        </div>
    </div>
{% endblock %}

Projects/templates/Projects/update.html
{% include 'base.html' %}
{% block body %}

    <div class="container px-4 py-5 px-md-5 text-center text-lg-start my-5">
        <div class="row gx-lg-5 align-items-center mb-5">
            <div class="col-lg-3 mb-5 mb-lg-0" style="z-index: 10">
                <h1>Update Project</h1>
            </div>

            <div class="col-lg-6 mb-5 mb-lg-0 position-relative">
                <div id="radius-shape-1" class="position-absolute rounded-circle shadow-5-strong"></div>
                <div id="radius-shape-2" class="position-absolute shadow-5-strong"></div>

                <div class="card bg-glass" style="background-color: rgba(87,101,107,0.5); color: #ced6de">
                    <div class="card-body px-4 py-5 px-md-5">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-6 mb-4 text-center container">
                                    <div class="form-outline">
                                        {{ form.as_div }}
                                    </div>
                                </div>
                            </div>
                            <button class="btn btn-primary container" type="submit">save</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}