Accounts/urls.py
from django.urls import path
from .views import LoginUser, ProfileUser, RegisterUser, LogoutUser, ChangePasswordUser, ProfileUpdateView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginUser.as_view(), name='user_login'),
    path('profile/', ProfileUser.as_view(), name='user_profile'),
    path('register/', RegisterUser.as_view(), name='user_register'),
    path('logout/', LogoutUser.as_view(), name='user_logout'),
    path('change/password/', ChangePasswordUser.as_view(), name='user_change_password'),
    path('profile/update/', ProfileUpdateView.as_view(), name='update_profile'),

]

ProjectManager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('Accounts.urls')),
    path('', include('Projects.urls')),
    path('', include('pwa.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% load pwa %}
{% progressive_web_app_meta %}
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'base.css' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% include 'navbar.html' %}
<br><br>
{% include 'message.html' %}
{% block content %}
{% endblock %}


</body>
</html>

templates/message.html
<div id="del_msg" dir="ltr">
    {% if messages %}
        {% for msg in messages %}
            <h3 {% if msg.tags %} class="alert alert-{{ msg.tags }}" {% endif %}> {{ msg }}</h3>
        {% endfor %}
    {% endif %}
</div>

templates/navbar.html
<nav class="navbar navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">ProjectManager</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar"
                aria-controls="offcanvasDarkNavbar" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar"
             aria-labelledby="offcanvasDarkNavbarLabel">
            <div class="offcanvas-header">
                <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">{% if user.is_authenticated %}@{{ user.username }}{% else %}Guest{% endif %}</h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas"
                        aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
                <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">New Project</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            Project tree
                        </a>
                        <ul class="dropdown-menu dropdown-menu-dark">
                            <li><a class="dropdown-item" href="#">project</a></li>
                            <hr class="dropdown-divider">
                            <li><a class="dropdown-item" href="#">task</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="">subtask</a></li>
                        </ul>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            Profile
                        </a>

                        <ul class="dropdown-menu dropdown-menu-dark">
                            <li><a class="dropdown-item" href="{% url 'accounts:user_profile' %}">profile</a></li>
                            <hr class="dropdown-divider">
                            <li><a class="dropdown-item" href="{% url 'accounts:user_logout' %}">logout</a></li>
                        </ul>

                    </li>
                    {% elif not user.is_authenticated %}
                        <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            login/register
                        </a>

                        <ul class="dropdown-menu dropdown-menu-dark">
                            <li><a class="dropdown-item" href="{% url 'accounts:user_register' %}">register</a></li>
                            <hr class="dropdown-divider">
                            <li><a class="dropdown-item" href="{% url 'accounts:user_login' %}">login</a></li>
                        </ul>

                    </li>
                    {% endif %}


                </ul>
                <form class="d-flex mt-3" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </div>
</nav>